---
sudo: required
dist: trusty

language: python
python: "2.7"

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y unzip wget
  - pip install ansible
  - pip install ansible-lint
  - wget -O packer.zip https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - sudo unzip -o packer.zip -d /usr/local/bin/
  - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip
  - sudo unzip -o terraform.zip -d /usr/local/bin/
  - wget -O tflint.zip https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
  - sudo unzip -o tflint.zip -d /usr/local/bin/

script:
  - cd packer
  - packer validate -var-file=variables.json.example app.json
  - packer validate -var-file=variables.json.example db.json
  - cd ../terraform/stage
  - terraform init
  - terraform validate
  - tflint --error-with-issues
  - cd ../../ansible
  - ansible-lint playbooks/site.yml
